// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiL0gMEi_hQClJwgDgfy6olnv8nCas8g0',
    appId: '1:684161369571:web:32cc1c1070e37e4a550cd6',
    messagingSenderId: '684161369571',
    projectId: 'cruds1-97e9e',
    authDomain: 'cruds1-97e9e.firebaseapp.com',
    storageBucket: 'cruds1-97e9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QoYi9k0C18CHkJF5rnSWzC40JmYIUEE',
    appId: '1:684161369571:android:c0c682e0ff76d02e550cd6',
    messagingSenderId: '684161369571',
    projectId: 'cruds1-97e9e',
    storageBucket: 'cruds1-97e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81JIj8Z_prM0huf3KOFgq21JREDO49CQ',
    appId: '1:684161369571:ios:fdea45bb498a625e550cd6',
    messagingSenderId: '684161369571',
    projectId: 'cruds1-97e9e',
    storageBucket: 'cruds1-97e9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81JIj8Z_prM0huf3KOFgq21JREDO49CQ',
    appId: '1:684161369571:ios:fdea45bb498a625e550cd6',
    messagingSenderId: '684161369571',
    projectId: 'cruds1-97e9e',
    storageBucket: 'cruds1-97e9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiL0gMEi_hQClJwgDgfy6olnv8nCas8g0',
    appId: '1:684161369571:web:2ed233bf5589c4a9550cd6',
    messagingSenderId: '684161369571',
    projectId: 'cruds1-97e9e',
    authDomain: 'cruds1-97e9e.firebaseapp.com',
    storageBucket: 'cruds1-97e9e.firebasestorage.app',
  );
}
